// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalksAPI.Data;

#nullable disable

namespace NZWalksAPI.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20250924105814_Image")]
    partial class Image
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalksAPI.Models.Domains.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72c523de-27ac-4a30-b9f6-b89370250c3b"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("c4821f51-bcb3-45dd-beaf-92fe0457460e"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("2cb16262-dccf-40e6-971b-5a8ddc25c644"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalksAPI.Models.Domains.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("NZWalksAPI.Models.Domains.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e6b548f-55cf-4936-90d8-dec24ef01410"),
                            Code = "AKL",
                            Name = "Aukland",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Auckland_Marina_%28273797355%29.jpeg/1920px-Auckland_Marina_%28273797355%29.jpeg"
                        },
                        new
                        {
                            Id = new Guid("1eed54c3-5ba5-44ae-b8b4-d5b2695537d3"),
                            Code = "WLG",
                            Name = "Wellington",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Wellington_City_from_Mt_Victoria_looking_towards_the_Basin_Reserve_and_City_Centre_%282%29.jpg/1920px-Wellington_City_from_Mt_Victoria_looking_towards_the_Basin_Reserve_and_City_Centre_%282%29.jpg"
                        },
                        new
                        {
                            Id = new Guid("f4d2b3f1-2dcb-4c8a-9c8a-2b5f6e3e8e3a"),
                            Code = "CHC",
                            Name = "Christchurch",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Christchurch_City_Centre_from_Bridge_of_Remembrance_looking_south_%282%29.jpg/1920px-Christchurch_City_Centre_from_Bridge_of_Remembrance_looking_south_%282%29.jpg"
                        },
                        new
                        {
                            Id = new Guid("d3b5c6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Code = "HML",
                            Name = "Hamilton",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Hamilton_City_Centre_from_Hamilton_Lake_looking_north_%282%29.jpg/1920px-Hamilton_City_Centre_from_Hamilton_Lake_looking_north_%282%29.jpg"
                        });
                });

            modelBuilder.Entity("NZWalksAPI.Models.Domains.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalksAPI.Models.Domains.Walk", b =>
                {
                    b.HasOne("NZWalksAPI.Models.Domains.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalksAPI.Models.Domains.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
